services:
  analyzerlextaticoapi:
    image: ${DOCKER_REGISTRY-}lextaticoapi
    container_name: analyzer_lextatico_api_prd
    build:
      context: .
      dockerfile: src/Analyzer.Lextatico.Api/Dockerfile
    networks:
      - Lextatico
    ports:
      - 9004:9004
      - 9005:9005
