services:
  analyzerlextaticoapi:
    image: ${DOCKER_REGISTRY-}analyzerlextaticoapi
    container_name: analyzer_lextatico_api
    build:
      context: .
      dockerfile: src/Analyzer.Lextatico.Api/Dockerfile-debug
    networks:
      - Lextatico
    ports:
      - 9004:9004
      - 9005:9005
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOCAL_DEVELOPMENT=True
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
