INSERT INTO TerminalToken (Name, Lexeme, TokenType)
VALUES ('Identificador 1', '^[a-zA-Z_][a-zA-Z0-9_]*', 'AlphaNumDashIdentifier'),
       ('Identificador 2', '^[a-zA-Z][a-zA-Z0-9]*', 'AlphaNumIdentifier'),
       ('Identificador 3', '^[a-zA-Z]+', 'AlphaIdentifier'),
       ('Int', 'int', 'KeyWord'),
       ('Char', 'char', 'KeyWord'),
       ('Double', 'double', 'KeyWord'),
       ('String', 'string', 'KeyWord'),
       ('Ponto', '.', 'SugarToken'),
       ('Vírgula', ',', 'SugarToken'),
       ('Ponto e vírgula', ';', 'SugarToken'),
       ('Igual', '==', 'SugarToken'),
       ('Menor ou igual', '<=', 'SugarToken'),
       ('Maior ou igual', '>=', 'SugarToken'),
       ('Diferente', '!=', 'SugarToken'),
       ('Parêntese esquerdo', '(', 'SugarToken'),
       ('Parêntese direito', ')', 'SugarToken'),
       ('Chave esquerda', '{', 'SugarToken'),
       ('Chave direita', '}', 'SugarToken');
