INSERT INTO TerminalToken (Name, Lexeme, TokenType)
VALUES ('Identificador 1', '^[a-zA-Z_][a-zA-Z0-9_]*', 'AlphaNumDashIdentifier'),
       ('Identificador 2', '^[a-zA-Z][a-zA-Z0-9]*', 'AlphaNumIdentifier'),
       ('Identificador 3', '^[a-zA-Z]+', 'AlphaIdentifier'),
       ('Texto', '^\"[a-zA-Z0-9\s]+\"', 'String'),
       ('Inteiro', '^[+|-]?[0-9]+', 'Integer'),
       ('Real', '^[+|-]?[0-9]+\.[0-9]+', 'Float'),
       ('Int', 'int', 'KeyWord'),
       ('Char', 'char', 'KeyWord'),
       ('Float', 'float', 'KeyWord'),
       ('String', 'string', 'KeyWord'),
       ('Verdadeiro', 'true', 'KeyWord'),
       ('Falso', 'false', 'Keyword'),
       ('Vazio', 'void', 'Keyword'),
       ('If', 'if', 'Keyword'),
       ('Else', 'else', 'Keyword'),
       ('Switch', 'switch', 'Keyword'),
       ('Case', 'case', 'Keyword'),
       ('Break', 'break', 'KeyWord'),
       ('Default', 'default', 'KeyWord'),
       ('While', 'while', 'KeyWord'),
       ('For', 'for', 'KeyWord'),
       ('Return', 'return', 'KeyWord'),
       ('Atribuição', '=', 'SugarToken'),
       ('Soma e atribuição', '+=', 'SugarToken'),
       ('Subtração e atribuição', '-=', 'SugarToken'),
       ('Multiplicação e atribuição', '*=', 'SugarToken'),
       ('Divisão e atribuição', '/=', 'SugarToken'),
       ('Ponto', '.', 'SugarToken'),
       ('Igual', '==', 'SugarToken'),
       ('Menor ou igual', '<=', 'SugarToken'),
       ('Maior ou igual', '>=', 'SugarToken'),
       ('Diferente', '!=', 'SugarToken'),
       ('Incremento', '++', 'SugarToken'),
       ('Decremento', '--', 'SugarToken'),
       ('Vírgula', ',', 'SugarToken'),
       ('Ponto e vírgula', ';', 'SugarToken'),
       ('Dois pontos', ':', 'SugarToken'),
       ('Soma', '+', 'SugarToken'),
       ('Subtração', '-', 'SugarToken'),
       ('Multiplicação', '*', 'SugarToken'),
       ('Divisão', '/', 'SugarToken'),
       ('Parêntese esquerdo', '(', 'SugarToken'),
       ('Parêntese direito', ')', 'SugarToken'),
       ('Chave esquerda', '{', 'SugarToken'),
       ('Chave direita', '}', 'SugarToken');
