INSERT INTO TerminalToken (Name, ViewName, Resume, Lexeme, TokenType, IdentifierType)
VALUES ('Identificador 1', 'ID1', 'Identificador com apenas letras. Ex: test', '^[a-zA-Z]+', 'Identifier', 'Alpha'),
       ('Identificador 2', 'ID2', 'Identificador com letras e números. Ex: test1', '^[a-zA-Z][a-zA-Z0-9]*', 'Identifier', 'AlphaNum'),
       ('Identificador 3', 'ID3', 'Identificador com letras, números e traço. Ex: _test1', '^[a-zA-Z_][a-zA-Z0-9_]*', 'Identifier', 'AlphaNumDash'),
       ('Texto', 'TEXT', 'Sequência de caracteres entre ("). Ex: "Lorem ipsum"', '^\"[a-zA-Z0-9\s]+\"', 'String', null),
       ('Inteiro', 'NINTEGER', 'Um número inteiro. Ex: 125', '^[+|-]?[0-9]+', 'Integer', null),
       ('Real', 'NFLOAT', 'Um número real. Ex: 125.5', '^[+|-]?[0-9]+\.[0-9]+', 'Float', null),
       ('Int', 'INT', 'Palavra reservada "int"',  'int', 'KeyWord', null),
       ('Char', 'CHAR', 'Palavra reservada "char"', 'char', 'KeyWord', null),
       ('Float', 'FLOAT', 'Palavra reservada "float"', 'float', 'KeyWord', null),
       ('String', 'STRING', 'Palavra reservada "string"', 'string', 'KeyWord', null),
       ('Verdadeiro', 'TRUE', 'Palavra reservada "true"', 'true', 'KeyWord', null),
       ('Falso', 'FALSE', 'Palavra reservada "false"', 'false', 'Keyword', null),
       ('Vazio', 'VOID', 'Palavra reservada "void"', 'void', 'Keyword', null),
       ('If', 'IF', 'Palavra reservada "if"', 'if', 'Keyword', null),
       ('Else', 'ELSE', 'Palavra reservada "else"', 'else', 'Keyword', null),
       ('Switch', 'SWITCH', 'Palavra reservada "switch"', 'switch', 'Keyword', null),
       ('Case', 'CASE', 'Palavra reservada "case"', 'case', 'Keyword', null),
       ('Break', 'BREAK', 'Palavra reservada "break"', 'break', 'KeyWord', null),
       ('Default', 'DEFAULT', 'Palavra reservada "default"', 'default', 'KeyWord', null),
       ('While', 'WHILE', 'Palavra reservada "while"', 'while', 'KeyWord', null),
       ('For', 'FOR', 'Palavra reservada "for"', 'for', 'KeyWord', null),
       ('Return', 'RETURN', 'Palavra reservada "return"', 'return', 'KeyWord', null),
       ('Atribuição', 'ASSIGN', 'Operador de atribuição "="', '=', 'SugarToken', null),
       ('Soma e atribuição', 'PLUSASSIGN', 'Operador de soma e atribuição "+="', '+=', 'SugarToken', null),
       ('Subtração e atribuição', 'MINUSASSIGN', 'Operador de subtração e atribuição "-="', '-=', 'SugarToken', null),
       ('Multiplicação e atribuição', 'MULTIASSIGN', 'Operador de multiplicação e atribuição "*="', '*=', 'SugarToken', null),
       ('Divisão e atribuição', 'DIVIDEASSIGN', 'Operador de divisão e atribuição "/="', '/=', 'SugarToken', null),
       ('Ponto', 'DOT', 'Símbolo "."', '', 'SugarToken', null),
       ('Igual', 'EQUAL', 'Operador igual "=="', '==', 'SugarToken', null),
       ('Menor', 'LESSER', 'Operador menor "<"', '<', 'SugarToken', null),
       ('Menor ou igual', 'LESSEREQUAL', 'Operador menor ou igual "<="', '<=', 'SugarToken', null),
       ('Maior', 'GREATER', 'Operador maior ">"', '>', 'SugarToken', null),
       ('Maior ou igual', 'GREATEREQUAL', 'Operador maior ou igual ">="', '>=', 'SugarToken', null),
       ('Diferente', 'DIFFERENT', 'Operador diferente "!="', '!=', 'SugarToken', null),
       ('Incremento', 'INCREMENT', 'Operador de incremento "++"', '++', 'SugarToken', null),
       ('Decremento', 'DECREMENT', 'Operador de decremento "--"', '--', 'SugarToken', null),
       ('Vírgula', 'COMMA', 'Símbolo ","', ',', 'SugarToken', null),
       ('Ponto e vírgula', 'SEMICOLON', 'Símbolo ";"', ';', 'SugarToken', null),
       ('Dois pontos', 'COLON', 'Símbolo ":"', ':', 'SugarToken', null),
       ('Soma', 'PLUS', 'Operador de soma "+"', '+', 'SugarToken', null),
       ('Subtração', 'MINUS', 'Operador de subtração "-"', '-', 'SugarToken', null),
       ('Multiplicação', 'MULTI', 'Operador de multiplicação "*"', '*', 'SugarToken', null),
       ('Divisão', 'DIVIDE', 'Operador de divisão "/"', '/', 'SugarToken', null),
       ('Parêntese esquerdo', 'LPAREN', 'Símbolo "("', '(', 'SugarToken', null),
       ('Parêntese direito', 'RPAREN', 'Símbolo ")"', ')', 'SugarToken', null),
       ('Chave esquerda', 'LBRACKET', 'Símbolo "{"', '{', 'SugarToken', null),
       ('Chave direita', 'RBRACKET', 'Símbolo "}"', '}', 'SugarToken', null);
